Team Members

*   Libin Kutty - Group 2
*   Ritu Gahir - Group 3
*   Viju Sudhi - Group 10


In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import time
import os

# Task 1

Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.

In [0]:
@tf.function
def task1():
  t1 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)

  topk = tf.math.top_k(t1, k=5, sorted=True, name=None) # provides the indices of the top k values in each row 

  tf.print(topk)

In [0]:
task1()

TopKV2(values=[[0.93601346 0.72878027 0.616193414 0.609738946 0.516572]
 [0.917227507 0.758565664 0.696338296 0.534991741 0.484563351]
 [0.936653256 0.614828229 0.607205749 0.516776443 0.423364043]
 ...
 [0.860462666 0.669502616 0.659667492 0.564227939 0.411240339]
 [0.912312031 0.829636574 0.5374192 0.345035791 0.339137077]
 [0.97267592 0.906300187 0.799423 0.785806656 0.676722288]], indices=[[6 3 0 1 5]
 [1 4 5 9 0]
 [3 0 5 6 9]
 ...
 [3 0 9 8 5]
 [6 5 1 7 0]
 [9 1 0 3 6]])


# Task 2

Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.


In [0]:
#@tf.function
def task2():
  t2 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32)
 
  max = tf.math.argmax(t2, axis=1, output_type=tf.dtypes.int64, name=None)
 
  tf.print(max)  # array of indices with maximum value 
 
  z = tf.Variable(tf.zeros([10,10], tf.float32))
  for i, ind in enumerate(max):
    z[i,ind].assign(1.0)
 
  tf.print(z)

In [0]:
task2()

[1 5 4 ... 2 8 3]
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


# Task 3

As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.

In [0]:
#@tf.function
def task3():

  t3 = tf.random.uniform((10,10), minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None) # intialise a 2d tensor
  o3 = tf.Variable(tf.zeros(t3.shape, dtype=tf.dtypes.float32, name=None)) # initialise a tensor with zeroes 2d

  topk = tf.math.top_k(t3, k=5, sorted=True, name=None) # find top k 

  index = topk.indices  
  tf.print(index)

  for i,ind in enumerate(index):  # iterate over the index of top k  [i is for rows and j is for the value of index ]
    for j in ind:
      o3[i,j].assign(t3[i,j])

  tf.print(o3)


In [0]:
task3()

[[7 3 5 0 8]
 [7 1 9 6 0]
 [9 4 7 2 6]
 ...
 [1 5 2 0 6]
 [5 9 1 7 6]
 [8 5 6 1 4]]
[[0.526077867 0 0 ... 0.878371716 0.485516429 0]
 [0.470251441 0.914644718 0 ... 0.988374 0 0.773713708]
 [0 0 0.625819325 ... 0.763696551 0 0.969604373]
 ...
 [0.53341794 0.978401542 0.84759438 ... 0 0 0]
 [0 0.709913254 0 ... 0.623722076 0 0.77282095]
 [0 0.329927802 0 ... 0 0.850263953 0]]


# Task 4

Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.

In [0]:
#@tf.function
def task4():
  t4 = tf.random.uniform([10], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  a = 0.5

  z = tf.Variable(tf.zeros([10], tf.float32))

  for i,t in enumerate(t4):
    if i == 0:
      z[i].assign(t)
    else:
      z[i].assign(a * z[i-1] + (1-a) * t) # t is value from original tensor

  tf.print(t4)

  tf.print(z)

In [0]:
task4()

[0.759301424 0.909891486 0.126375318 ... 0.562464595 0.789613485 0.592609525]
[0.759301424 0.834596455 0.480485886 ... 0.421719521 0.605666518 0.599138]


# Task 5

Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it).

In [0]:
#@tf.function
def task5():
  n = 10
  t5 = tf.random.uniform([n], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)
  a = 0.5

  z = tf.Variable(tf.zeros([n], tf.float32))

  tf.print(t5)
  tf.print(t5[n-1:]) # last value of input tensor 

  a = a * z[n-2:][0] + (1-a) * t5[n-1:][0]   #using the second last value and the last value 
  #z[n-1:].assign(a)

  tf.print(a)

In [0]:
task5()

[0.105722547 0.778939128 0.901049495 ... 0.699404716 0.401079893 0.622471094]
[0.622471094]
0.311235547


# Task 6

Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.

In [0]:
#@tf.function
def task6():
  n = tf.constant(2)
  m = tf.constant(5)
  x = tf.random.uniform((n,m), minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)
  y = tf.random.uniform((n,m), minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)
  z = tf.random.uniform((n,m), minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)

  t6 = tf.Variable(tf.zeros((n,m), tf.int32))
  #print(x)
  for i,a in enumerate(x): # i is the row and a is the list of values in row i
    #print(i,a)
    for j,b in enumerate(a):
      #print(j,b)
      if (b % 2) == 0:
        t6[i,j].assign(y[i,j])
      else:
        t6[i,j].assign(z[i,j])

  tf.print('X')
  tf.print(x)
  tf.print('Y')
  tf.print(y)
  tf.print('Z')
  tf.print(z)

  tf.print('New Tensor')
  tf.print(t6)

In [0]:
task6()

X
[[5 6 9 2 5]
 [5 8 1 7 6]]
Y
[[2 7 0 4 3]
 [4 5 8 1 8]]
Z
[[9 0 8 9 4]
 [2 1 8 1 5]]
New Tensor
[[9 7 8 4 4]
 [2 5 8 1 8]]


# Task 7

Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.

In [0]:
@tf.function
def task7(): 
  n = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None) #dim1
  m = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None) #dim2

  t7 = tf.random.uniform((n[0],m[0]), minval=0, maxval=10, dtype=tf.dtypes.float32, seed=None, name=None)

  #last_dim = t7.shape[-1]
  last_dim = tf.shape(t7)[-1]

  if tf.math.greater(last_dim, 100):
    value = 100
  elif tf.math.less_equal(last_dim, 100) and tf.math.greater(last_dim, 44):
    value = 12
  else:
    value = 0

  tf.print(last_dim)
  tf.print(value)

In [0]:
task7()

131
100


# Task 8

As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?

In [0]:
@tf.function
def task8():
  count1 = 0
  count2 = 0
  count3 = 0
  for _ in range(10): 
    n = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)
    m = tf.random.uniform([1], minval=1, maxval=200, dtype=tf.dtypes.int32, seed=None, name=None)

    t8 = tf.random.uniform((n[0],m[0]), minval=0, maxval=10, dtype=tf.dtypes.float32, seed=None, name=None)
    last_dim = tf.shape(t8)[-1]

    if tf.math.greater(last_dim, 100):
      value = 100
      count1 += 1
    elif tf.math.less_equal(last_dim, 100) and tf.math.greater(last_dim, 44):
      value = 12
      count2 += 1
    else:
      value = 0
      count3 += 1

  tf.print('Count 1:',count1)
  tf.print('Count 2:', count2)
  tf.print( 'Count 3:', count3)


In [0]:
task8()

Count 1: 6
Count 2: 3
Count 3: 1


# Task 9

Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.

In [0]:
@tf.function
def task9():
  n = 2

  x = tf.random.uniform([n], minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)
  y = tf.random.uniform([n], minval=0, maxval=10, dtype=tf.dtypes.int32, seed=None, name=None)


### How to do it without repeating the steps if the n increases ??
  t9_1 = tf.broadcast_to(tf.math.add(x[0],-y), [n])
  t9_2 = tf.broadcast_to(tf.math.add(x[-1],-y), [n])

  t9 = tf.stack([t9_1, t9_2])


  tf.print(x)
  tf.print(y)
  tf.print(t9)


In [0]:
task9()

[1 6]
[5 9]
[[-4 -8]
 [1 -3]]


# Task 10

Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.


In [0]:
@tf.function
def task10(alpha):
  batch = 10
  time = 3
  feature = 5

  h = tf.random.uniform([batch, time, feature], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None) # encoder states h of shape batch x time x feature
  s = tf.random.uniform([batch, feature], minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None) # decoded -- size batch x feature
  s = tf.transpose(s) #[feature x batch]

  for i in tf.range(time):
    x = tf.matmul(h[:, i,:], s)  #alpha[:, i] is equal to h[:, i] * s 
    #print('x',x.shape)   ---> x (10, 10)

    sum = tf.reduce_sum(x,1)  # sum of values across row 
    #print('sum',sum.shape) --->  sum (10,)
    alpha[:, i].assign(sum)

  tf.print(alpha)
  tf.print(alpha.shape)


In [0]:
batch = 10
time = 3
alpha = tf.Variable(tf.zeros((batch, time), tf.float32)) # alpha should be of shape batch x time
task10(alpha)

[[14.3753147 15.0172606 12.3402348]
 [11.3158751 18.7180901 18.7907505]
 [15.2906513 8.50006676 16.8741951]
 ...
 [10.3203478 9.84994793 11.7469397]
 [9.77268887 15.3767529 12.6676283]
 [12.5030489 7.05182266 13.1771765]]
TensorShape([10, 3])
